version: "3"

services:
  user-app:
    container_name: userservice-container
    build:
      context: .
      dockerfile: src/User.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      - db
      - todo-app

  todo-app:
    container_name: todo-container
    build:
      context: .
      dockerfile: src/ToDo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Test
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"

  db:
    build:
      context: .
      dockerfile: .build/Dockerfile.mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sa
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: UserDB

  sqlapi:
    container_name: sqlapi
    image: techciceksepeti/sqlapi:1.6
    ports:
      - "8033:8033"

  mountebank:
    build:
      context: .
      dockerfile: .build/Dockerfile.mountebank
    container_name: mountebank
    ports:
      - "2525:2525"

  postman_checks:
      container_name: postman
      build:
        context: .
        dockerfile: .build/Dockerfile.newman
      image: postman_checks
      command:
        run https://www.getpostman.com/collections/c0e728974a070f76869a
      volumes:
        - ./src:/etc/newman        